workspace 'DokuPaySdk'

target 'DokuPayDemo' do
    pod 'Masonry', '~> 1.1.0'
    pod 'ActionSheetPicker-3.0', '~> 2.5.0'
    pod 'JVFloatLabeledTextField', '~> 1.2.2'
    project 'DokuPayDemo/DokuPayDemo.xcodeproj'
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
      end
    end
end
